apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: janhavi2711/cicd-app:aaaecd3cbb59ca1861bb3b185c366f357c147d5a
        ports:
        - containerPort: 3000
